//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppEntities : DbContext
    {
        public AppEntities()
            : base("name=AppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_CUS_DOC_File> tbl_CUS_DOC_File { get; set; }
        public virtual DbSet<tbl_CUS_DOC_File_Actitity> tbl_CUS_DOC_File_Actitity { get; set; }
        public virtual DbSet<tbl_CUS_DOC_File_Permission> tbl_CUS_DOC_File_Permission { get; set; }
        public virtual DbSet<tbl_CUS_DOC_FileInFolder> tbl_CUS_DOC_FileInFolder { get; set; }
        public virtual DbSet<tbl_CUS_DOC_Folder> tbl_CUS_DOC_Folder { get; set; }
        public virtual DbSet<tbl_CUS_DOC_Folder_Activity> tbl_CUS_DOC_Folder_Activity { get; set; }
        public virtual DbSet<tbl_CUS_DOC_Folder_Permission> tbl_CUS_DOC_Folder_Permission { get; set; }
        public virtual DbSet<tbl_CUS_HRM_LIST_BoPhan> tbl_CUS_HRM_LIST_BoPhan { get; set; }
        public virtual DbSet<tbl_CUS_HRM_LIST_ChucDanh> tbl_CUS_HRM_LIST_ChucDanh { get; set; }
        public virtual DbSet<tbl_CUS_SYS_CauHinhHeThong> tbl_CUS_SYS_CauHinhHeThong { get; set; }
        public virtual DbSet<tbl_CUS_SYS_PermissionList> tbl_CUS_SYS_PermissionList { get; set; }
        public virtual DbSet<tbl_CUS_SYS_PermissionListDetailData> tbl_CUS_SYS_PermissionListDetailData { get; set; }
        public virtual DbSet<tbl_CUS_SYS_Role> tbl_CUS_SYS_Role { get; set; }
        public virtual DbSet<tbl_CUS_Version> tbl_CUS_Version { get; set; }
        public virtual DbSet<tbl_PAR_DonHang> tbl_PAR_DonHang { get; set; }
        public virtual DbSet<tbl_PAR_DonHang_ChiTiet> tbl_PAR_DonHang_ChiTiet { get; set; }
        public virtual DbSet<tbl_PAR_Partner> tbl_PAR_Partner { get; set; }
        public virtual DbSet<tbl_PAR_ThongTinSanPham> tbl_PAR_ThongTinSanPham { get; set; }
        public virtual DbSet<tbl_PROD_SanPham> tbl_PROD_SanPham { get; set; }
        public virtual DbSet<tbl_PROD_SanPham_ChiTiet> tbl_PROD_SanPham_ChiTiet { get; set; }
        public virtual DbSet<tbl_SYS_Apps> tbl_SYS_Apps { get; set; }
        public virtual DbSet<tbl_SYS_Config> tbl_SYS_Config { get; set; }
        public virtual DbSet<tbl_SYS_ControllerActions> tbl_SYS_ControllerActions { get; set; }
        public virtual DbSet<tbl_SYS_Form> tbl_SYS_Form { get; set; }
        public virtual DbSet<tbl_SYS_FormDetail> tbl_SYS_FormDetail { get; set; }
        public virtual DbSet<tbl_SYS_FormGroup> tbl_SYS_FormGroup { get; set; }
        public virtual DbSet<tbl_WEB_BaiViet_Tag> tbl_WEB_BaiViet_Tag { get; set; }
        public virtual DbSet<tbl_WEB_Tag> tbl_WEB_Tag { get; set; }
        public virtual DbSet<tbl_CUS_HRM_STAFF_NhanSu> tbl_CUS_HRM_STAFF_NhanSu { get; set; }
        public virtual DbSet<tbl_WEB_BaiViet> tbl_WEB_BaiViet { get; set; }
        public virtual DbSet<tbl_WEB_BaiViet_DanhMuc> tbl_WEB_BaiViet_DanhMuc { get; set; }
        public virtual DbSet<tbl_WEB_DanhMuc> tbl_WEB_DanhMuc { get; set; }
    }
}
